sudo: false
language: cpp

os: linux
dist: trusty

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

matrix:
  include:
    - env: COMPILER=clang++-5.0 BUILD_TYPE=Debug
      addons: &clang50
        apt:
          packages:
            - clang-5.0
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: COMPILER=clang++-5.0 BUILD_TYPE=Release
      addons: *clang50

    - env: COMPILER=g++-7 BUILD_TYPE=Debug
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - gcovr
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-7 BUILD_TYPE=Release
      addons: *gcc7

    - env: COMPILER=g++-7 BUILD_TYPE=Coverage
      addons: *gcc7

script:
  - mkdir build
  - ( cd build && cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make )
  - ( cd build && make test )

after_success:
  - bash run_coverage.sh
